
github:
  prebuilds:
    branches: true
    addComment: true
    addBadge: true
tasks:
  - before: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      npm install --location=global npm@latest typescript@latest markdownlint-cli
      curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
    init: |
      npm install
    command: 'npm run dev'
gitConfig:
  alias.st: status
  alias.co: checkout

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - usernamehw.errorlens
    - DavidAnson.vscode-markdownlint
