name: 🔨CI
on:
  push:
    branches:    
      - '**'
  pull_request:
    branches:    
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install --location=global npm@latest typescript@latest markdownlint-cli
          npm install
      - name: Lint
        run: |
          npm run lint
          npm run mdlint